before:
  hooks:
  - go mod download
builds:
- id: kubectl-operator
  main: ./
  binary: kubectl-operator
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  - ppc64le
  - s390x
  ignore:
  - goos: darwin
    goarch: arm64
  - goos: darwin
    goarch: ppc64le
  - goos: darwin
    goarch: s390x
  - goos: windows
    goarch: arm64
  - goos: windows
    goarch: ppc64le
  - goos: windows
    goarch: s390x

archives:
- builds:
  - kubectl-operator
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  wrap_in_directory: false
  format: tar.gz
  files:
  - LICENSE
